// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ChallengeQa.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Login do candidato")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class LoginDoCandidatoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Login do candidato", "  Como candidato\r\n  Quero acessar a área do candidato\r\n  Para visualizar minhas i" +
                "nformações após o cadastro", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Login.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
  await testRunner.GivenAsync("que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                    "re\" do nível \"Pós-graduação\" recebendo credenciais válidas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Login.feature", "Feature: Login do candidato\r\n  Como candidato\r\n  Quero acessar a área do candidat" +
                    "o\r\n  Para visualizar minhas informações após o cadastro\r\n\r\nBackground:\r\n  Given " +
                    "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softw" +
                    "are\" do nível \"Pós-graduação\" recebendo credenciais válidas\r\n\r\n    @Login\r\n    S" +
                    "cenario: Login com credenciais geradas no cadastro\r\n        When acesso a área d" +
                    "o candidato\r\n        And preencho o usuário e senha válidos\r\n        And clico e" +
                    "m \"Login\"\r\n        Then devo visualizar a página inicial da área do candidato\r\n\r" +
                    "\n    @LoginInvalido\r\n    Scenario Outline: Tentativa de login inválido\r\n        " +
                    "When acesso a área do candidato\r\n        And preencho usuário \"<usuario>\" e senh" +
                    "a \"<senha>\"\r\n        And clico em \"Login\"\r\n        Then devo visualizar a mensag" +
                    "em de erro <campo> \"<mensagem>\"\r\n\r\n    Examples:\r\n        | usuario         | se" +
                    "nha             | campo    | mensagem          |\r\n        | usuarioInvalido | su" +
                    "bscription      | usuário  | Usuário inválido  |\r\n        | candidato       | Se" +
                    "nha_inválida    | senha    | Senha inválida    |\r\n        | usuarioInvalido | Se" +
                    "nha_inválida    | usuário  | Usuário inválido  |\r\n        | usuarioInvalido | Se" +
                    "nha_inválida    | senha    | Senha inválida    |\r\n\r\n\r\n    @RecuperarUsuario\r\n   " +
                    " Scenario: Fluxo de recuperação de usuário\r\n        When acesso a área do candid" +
                    "ato\r\n        And preencho o usuário\r\n        And clico em \"Recuperar usuário\"\r\n " +
                    "       Then devo visualizar a tela de recuperação de usuário\r\n\r\n    @RecuperarUs" +
                    "uario\r\n    Scenario: Recuperação de usuário sem informar credenciais\r\n        Wh" +
                    "en acesso a área do candidato\r\n        And clico em \"Recuperar usuário\"\r\n       " +
                    " Then devo visualizar uma mensagem de erro solicitando o preenchimento do usuári" +
                    "o\r\n\r\n\r\n    @RedefinirSenha\r\n    Scenario: Fluxo de redefinição de senha\r\n      W" +
                    "hen acesso a área do candidato\r\n      And preencho o usuário\r\n      And clico em" +
                    " \"Redefinir senha\"\r\n      Then devo visualizar a tela de redefinição de senha\r\n\r" +
                    "\n    @RedefinirSenha\r\n    Scenario: Redefinição de senha sem informar credenciai" +
                    "s\r\n      When acesso a área do candidato\r\n      And clico em \"Redefinir senha\"\r\n" +
                    "      Then devo visualizar uma mensagem de erro solicitando a identificação do u" +
                    "suário\r\n\r\n\r\n\r\n      @Seguranca\r\n      Scenario: Tentativa de acesso direto sem l" +
                    "ogin\r\n        Given que acesso diretamente a URL da área do candidato sem estar " +
                    "autenticado\r\n        Then devo ser redirecionado para a tela de login\r\n\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Login.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Login do candidato", "  Como candidato\r\n  Quero acessar a área do candidato\r\n  Para visualizar minhas i" +
                        "nformações após o cadastro", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(1)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(3)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                            "re\" do nível \"Pós-graduação\" recebendo credenciais válidas", null, null, "e185864c49df815b9ce37164cafb0ecf")}), "44050a2c0d11405ebe94e9545f128776"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "@Login", "c854da11e419dc5c9a5a6c54804f6564")}), "Scenario", "Login com credenciais geradas no cadastro", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(9)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "373cdd0d8f092051a188c1ef628cafff"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "preencho o usuário e senha válidos", null, null, "3723bea5d2f4c858aa5d5106936a9749"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Login\"", null, null, "0e4e55fd3ef98f58b76e46a65c63ec79"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar a página inicial da área do candidato", null, null, "b9547d207ad2e75caa4024cc08b2f074")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "d5dd9bac82aa665396605c26ed2c82cb")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "@LoginInvalido", "2a224e47b9b4fb5990f42c156289ad01")}), "Scenario Outline", "Tentativa de login inválido", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(9)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "2026254a52b9495286475479f2f2b6a2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "preencho usuário \"<usuario>\" e senha \"<senha>\"", null, null, "831f2a7c388fc25c9baa0440bc09510b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Login\"", null, null, "eedd0de4a9a0ef5e8bc61cdfb319f5ff"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar a mensagem de erro <campo> \"<mensagem>\"", null, null, "0566a1aa0f167659b0ac7cc2a0edbbbf")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(9)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(11)), "usuario"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(29)), "senha"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(49)), "campo"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(60)), "mensagem")}), "ad1046537c838950ab9cfa34fa153546"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(9)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(11)), "usuarioInvalido"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(29)), "subscription"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(49)), "usuário"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(60)), "Usuário inválido")}), "a7343931e6d023568b4400f5320344a3"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(9)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(11)), "candidato"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(29)), "Senha_inválida"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(49)), "senha"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(60)), "Senha inválida")}), "3e99520d2143a151846392c5ca860e98"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(9)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(11)), "usuarioInvalido"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(29)), "Senha_inválida"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(49)), "usuário"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(60)), "Usuário inválido")}), "f1af982c39d9bb5b8d110e4aca266e40"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(9)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(11)), "usuarioInvalido"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(29)), "Senha_inválida"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(49)), "senha"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(60)), "Senha inválida")}), "0aef93b2b2461c5b82f4023ef86cb7fe")}), "f5d74cd18ea6f35eb2526ebb4f99e00d")}), "cd75487bfaa0205197684c70ea773020")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "@RecuperarUsuario", "d1534d7d29f53f519f14a7280cc00486")}), "Scenario", "Fluxo de recuperação de usuário", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(9)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "4bd9c92a4c414c52a64b9314cbf7a295"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "preencho o usuário", null, null, "c7271cd5026d7454a45b430c05fefd48"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Recuperar usuário\"", null, null, "a45455f171352552b07f55a2eefdbb3f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar a tela de recuperação de usuário", null, null, "1d2e835b162af15890a3542afb335efc")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "46884ff5144ff557a41f55788fa8f1e2")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "@RecuperarUsuario", "d58cf4e2196ee253a711e874b12fafab")}), "Scenario", "Recuperação de usuário sem informar credenciais", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(9)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "94adbea8a447f65c882802ccab5aafeb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Recuperar usuário\"", null, null, "bbe696408ba5375ba298f8416e77e6ef"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar uma mensagem de erro solicitando o preenchimento do usuário", null, null, "4f7d4fa0a7bcf555afa725f96910f506")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "2c2fa2fa5b31a85aa6eba0a7000c9da5")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(5)), "@RedefinirSenha", "926c0dc35ac09c57873a4b43748e497e")}), "Scenario", "Fluxo de redefinição de senha", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(7)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "29b0b2ce18faa0538a2120ce9123fcbd"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(7)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "preencho o usuário", null, null, "ba56ab3a2faaf95ba73cb6ade75f9af2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(7)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Redefinir senha\"", null, null, "c5f68266e7f27550b4aa15defd653bc7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(7)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar a tela de redefinição de senha", null, null, "8acb00ab05d32b558a35da299e083304")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e960563c6422f05981cabee3da369aef")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(53, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(5)), "@RedefinirSenha", "72e000164228f255b05edd975ff0b831")}), "Scenario", "Redefinição de senha sem informar credenciais", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(7)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "320d558d69ae2a5894f3e27c0efb1f63"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(7)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Redefinir senha\"", null, null, "26793748b90426598cc8d344d377920d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(7)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar uma mensagem de erro solicitando a identificação do usuário", null, null, "dfa5d86ffcac8d5a89d0744b5e5951fb")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0ad1e2e3a25d2d5c881a1623e95e3053")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(60, new System.Nullable<long>(7)), "@Seguranca", "ad7307d4182970578f18635c4261b805")}), "Scenario", "Tentativa de acesso direto sem login", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(62, new System.Nullable<long>(9)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que acesso diretamente a URL da área do candidato sem estar autenticado", null, null, "e519c7af5cfa7c5b8555861312b2cf6b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(63, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo ser redirecionado para a tela de login", null, null, "87d6d766ab896b55aafe9c9a9514b91c")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "f4ed09ee815be85dbd1284b5b590344d"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("2f15d1599195a750928b9d15165cae86", "Features/Login.feature", "Login com credenciais geradas no cadastro", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e185864c49df815b9ce37164cafb0ecf"}), "2d0568a3e3447c5fb3b4cdf4709438cc", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "373cdd0d8f092051a188c1ef628cafff"}), "801a96510609a75f8e240ed0b618b5c1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3723bea5d2f4c858aa5d5106936a9749"}), "8bf554119510405192633ac3d21213c0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário e senha válidos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0e4e55fd3ef98f58b76e46a65c63ec79"}), "d361a15263507f58bbf081b9e2b17254", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b9547d207ad2e75caa4024cc08b2f074"}), "c66fa89f1a32385e8cb5500a70f8062c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a página inicial da área do candidato")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "c854da11e419dc5c9a5a6c54804f6564")}), new System.Collections.Generic.List<string>(new string[] {
                                        "d5dd9bac82aa665396605c26ed2c82cb"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("8e131815398a925f9986f02b72e4f1c5", "Features/Login.feature", "Tentativa de login inválido", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e185864c49df815b9ce37164cafb0ecf"}), "4407b85d1d294d58af456aae9dca8e8c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2026254a52b9495286475479f2f2b6a2",
                                                        "a7343931e6d023568b4400f5320344a3"}), "197430e745373d5ba6479eeb36283b78", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "831f2a7c388fc25c9baa0440bc09510b",
                                                        "a7343931e6d023568b4400f5320344a3"}), "b42d99b08f6e42539916a4a8442a84ee", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho usuário \"usuarioInvalido\" e senha \"subscription\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "eedd0de4a9a0ef5e8bc61cdfb319f5ff",
                                                        "a7343931e6d023568b4400f5320344a3"}), "c20b75674ac99a5ba1f3cc969dff8f31", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0566a1aa0f167659b0ac7cc2a0edbbbf",
                                                        "a7343931e6d023568b4400f5320344a3"}), "f620039949e1fd5998816a4613a375ae", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a mensagem de erro usuário \"Usuário inválido\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@LoginInvalido", "2a224e47b9b4fb5990f42c156289ad01")}), new System.Collections.Generic.List<string>(new string[] {
                                        "cd75487bfaa0205197684c70ea773020",
                                        "a7343931e6d023568b4400f5320344a3"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("14722a6958492a538e46fd7ea811273a", "Features/Login.feature", "Tentativa de login inválido", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e185864c49df815b9ce37164cafb0ecf"}), "caaf0ecbc76a1f5d84351b92732199fc", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2026254a52b9495286475479f2f2b6a2",
                                                        "3e99520d2143a151846392c5ca860e98"}), "883b401586efe45b9220308047b77dc0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "831f2a7c388fc25c9baa0440bc09510b",
                                                        "3e99520d2143a151846392c5ca860e98"}), "e2555682b741c05eb6ef4d186bbb4053", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho usuário \"candidato\" e senha \"Senha_inválida\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "eedd0de4a9a0ef5e8bc61cdfb319f5ff",
                                                        "3e99520d2143a151846392c5ca860e98"}), "2314cb48d889e25ca9f6a8fe3f8e3170", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0566a1aa0f167659b0ac7cc2a0edbbbf",
                                                        "3e99520d2143a151846392c5ca860e98"}), "256253ab85c00e5794a3a98490a6672a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a mensagem de erro senha \"Senha inválida\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@LoginInvalido", "2a224e47b9b4fb5990f42c156289ad01")}), new System.Collections.Generic.List<string>(new string[] {
                                        "cd75487bfaa0205197684c70ea773020",
                                        "3e99520d2143a151846392c5ca860e98"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("1eef4ccc93092e569b17f1cefcad004b", "Features/Login.feature", "Tentativa de login inválido", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e185864c49df815b9ce37164cafb0ecf"}), "26be7e6f0b43e159bc4bff03512149f6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2026254a52b9495286475479f2f2b6a2",
                                                        "f1af982c39d9bb5b8d110e4aca266e40"}), "44d3f2690fa5cb599374bdf172eb8962", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "831f2a7c388fc25c9baa0440bc09510b",
                                                        "f1af982c39d9bb5b8d110e4aca266e40"}), "6eaa454b0e641c59934de83b02d79055", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho usuário \"usuarioInvalido\" e senha \"Senha_inválida\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "eedd0de4a9a0ef5e8bc61cdfb319f5ff",
                                                        "f1af982c39d9bb5b8d110e4aca266e40"}), "fd191450c687a65bb47f47c61fdeaf3e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0566a1aa0f167659b0ac7cc2a0edbbbf",
                                                        "f1af982c39d9bb5b8d110e4aca266e40"}), "73a9b325789b575e9e43e65b866f5460", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a mensagem de erro usuário \"Usuário inválido\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@LoginInvalido", "2a224e47b9b4fb5990f42c156289ad01")}), new System.Collections.Generic.List<string>(new string[] {
                                        "cd75487bfaa0205197684c70ea773020",
                                        "f1af982c39d9bb5b8d110e4aca266e40"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3d5ffc488fa9c154b5de5c3659a689c4", "Features/Login.feature", "Tentativa de login inválido", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e185864c49df815b9ce37164cafb0ecf"}), "f82f1a62894a52548ff888c2c8cbf9b1", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2026254a52b9495286475479f2f2b6a2",
                                                        "0aef93b2b2461c5b82f4023ef86cb7fe"}), "86389c84e338ac5bbe5af2bce636061d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "831f2a7c388fc25c9baa0440bc09510b",
                                                        "0aef93b2b2461c5b82f4023ef86cb7fe"}), "f9d26d999228225dbfbb626e850294fc", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho usuário \"usuarioInvalido\" e senha \"Senha_inválida\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "eedd0de4a9a0ef5e8bc61cdfb319f5ff",
                                                        "0aef93b2b2461c5b82f4023ef86cb7fe"}), "082e5e80bda3f359b4312313489f4171", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0566a1aa0f167659b0ac7cc2a0edbbbf",
                                                        "0aef93b2b2461c5b82f4023ef86cb7fe"}), "78d42f587714215286f15e8856aeed9b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a mensagem de erro senha \"Senha inválida\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@LoginInvalido", "2a224e47b9b4fb5990f42c156289ad01")}), new System.Collections.Generic.List<string>(new string[] {
                                        "cd75487bfaa0205197684c70ea773020",
                                        "0aef93b2b2461c5b82f4023ef86cb7fe"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("e1c9ffce9fbd1754aa833e798706ada6", "Features/Login.feature", "Fluxo de recuperação de usuário", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e185864c49df815b9ce37164cafb0ecf"}), "75b2f4ba0827a858a183809d813ceac3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4bd9c92a4c414c52a64b9314cbf7a295"}), "4705a01bfdbbc856b2a0dadaa980194d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c7271cd5026d7454a45b430c05fefd48"}), "14fa5b2745c9ad51a6e09e727180e98c", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a45455f171352552b07f55a2eefdbb3f"}), "07d65f746f1db8558ec36bf23509c8f8", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Recuperar usuário\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1d2e835b162af15890a3542afb335efc"}), "a0c6fa35529666548a3daaf821cbe234", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a tela de recuperação de usuário")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@RecuperarUsuario", "d1534d7d29f53f519f14a7280cc00486")}), new System.Collections.Generic.List<string>(new string[] {
                                        "46884ff5144ff557a41f55788fa8f1e2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("8532fc1cc24458538bbd44e26540a12c", "Features/Login.feature", "Recuperação de usuário sem informar credenciais", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e185864c49df815b9ce37164cafb0ecf"}), "53fd6c0bf68ccd59a3eaa873250ff481", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "94adbea8a447f65c882802ccab5aafeb"}), "cc56cfdcc7df2759b823fcf100c80ff1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bbe696408ba5375ba298f8416e77e6ef"}), "e94971654f45b158a2c3253a40d22a3e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Recuperar usuário\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4f7d4fa0a7bcf555afa725f96910f506"}), "a17db5aaad88a951a0691061e8bb64cc", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar uma mensagem de erro solicitando o preenchimento do usuário")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@RecuperarUsuario", "d58cf4e2196ee253a711e874b12fafab")}), new System.Collections.Generic.List<string>(new string[] {
                                        "2c2fa2fa5b31a85aa6eba0a7000c9da5"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("76fd82c415ea8c52bcff08a1ef0b2fc8", "Features/Login.feature", "Fluxo de redefinição de senha", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e185864c49df815b9ce37164cafb0ecf"}), "de233155d5b81f52883ea834d88f02cb", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "29b0b2ce18faa0538a2120ce9123fcbd"}), "191904a11032485c83ee2e3960ffdaca", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ba56ab3a2faaf95ba73cb6ade75f9af2"}), "c86db56ec522fd548c44733337235864", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c5f68266e7f27550b4aa15defd653bc7"}), "a11d3b629d3ffa50a7c2c6d5deba2799", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Redefinir senha\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8acb00ab05d32b558a35da299e083304"}), "94ce5fd2e4d4f35e98cac8ceef51412e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a tela de redefinição de senha")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@RedefinirSenha", "926c0dc35ac09c57873a4b43748e497e")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e960563c6422f05981cabee3da369aef"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("c25d8fd4ef3b2b568d96a404bd295759", "Features/Login.feature", "Redefinição de senha sem informar credenciais", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e185864c49df815b9ce37164cafb0ecf"}), "cedab6599e0a885eb1cf46f825f7e5bb", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "320d558d69ae2a5894f3e27c0efb1f63"}), "6ae3a85bcad8d450ab56deb9be990dfa", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "26793748b90426598cc8d344d377920d"}), "dbd9372cc370aa50961944b92096da2d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Redefinir senha\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "dfa5d86ffcac8d5a89d0744b5e5951fb"}), "5422e451ca13e353a19dc7126c5020b5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar uma mensagem de erro solicitando a identificação do usuário")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@RedefinirSenha", "72e000164228f255b05edd975ff0b831")}), new System.Collections.Generic.List<string>(new string[] {
                                        "0ad1e2e3a25d2d5c881a1623e95e3053"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d50d6902f94b1653801788d4ecffaf45", "Features/Login.feature", "Tentativa de acesso direto sem login", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e185864c49df815b9ce37164cafb0ecf"}), "98008c86e235c658a49d6850ab8766df", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e519c7af5cfa7c5b8555861312b2cf6b"}), "b8af8826917b8d5f910a8f4c971fe382", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso diretamente a URL da área do candidato sem estar autenticado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "87d6d766ab896b55aafe9c9a9514b91c"}), "69eac5af4f0f205e88dc45dd1258bcee", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo ser redirecionado para a tela de login")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Seguranca", "ad7307d4182970578f18635c4261b805")}), new System.Collections.Generic.List<string>(new string[] {
                                        "f4ed09ee815be85dbd1284b5b590344d"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(LoginDoCandidatoFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(LoginDoCandidatoFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(LoginDoCandidatoFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Login com credenciais geradas no cadastro")]
        [global::NUnit.Framework.CategoryAttribute("Login")]
        public async global::System.Threading.Tasks.Task LoginComCredenciaisGeradasNoCadastro()
        {
            string[] tagsOfScenario = new string[] {
                    "Login"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login com credenciais geradas no cadastro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 11
        await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
        await testRunner.AndAsync("preencho o usuário e senha válidos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
        await testRunner.AndAsync("clico em \"Login\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
        await testRunner.ThenAsync("devo visualizar a página inicial da área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tentativa de login inválido")]
        [global::NUnit.Framework.CategoryAttribute("LoginInvalido")]
        [global::NUnit.Framework.TestCaseAttribute("usuarioInvalido", "subscription", "usuário", "Usuário inválido", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("candidato", "Senha_inválida", "senha", "Senha inválida", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("usuarioInvalido", "Senha_inválida", "usuário", "Usuário inválido", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("usuarioInvalido", "Senha_inválida", "senha", "Senha inválida", "4", null)]
        public async global::System.Threading.Tasks.Task TentativaDeLoginInvalido(string usuario, string senha, string campo, string mensagem, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "LoginInvalido"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("usuario", usuario);
            argumentsOfScenario.Add("senha", senha);
            argumentsOfScenario.Add("campo", campo);
            argumentsOfScenario.Add("mensagem", mensagem);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentativa de login inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 18
        await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
        await testRunner.AndAsync(string.Format("preencho usuário \"{0}\" e senha \"{1}\"", usuario, senha), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
        await testRunner.AndAsync("clico em \"Login\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
        await testRunner.ThenAsync(string.Format("devo visualizar a mensagem de erro {0} \"{1}\"", campo, mensagem), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Fluxo de recuperação de usuário")]
        [global::NUnit.Framework.CategoryAttribute("RecuperarUsuario")]
        public async global::System.Threading.Tasks.Task FluxoDeRecuperacaoDeUsuario()
        {
            string[] tagsOfScenario = new string[] {
                    "RecuperarUsuario"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fluxo de recuperação de usuário", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 33
        await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
        await testRunner.AndAsync("preencho o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
        await testRunner.AndAsync("clico em \"Recuperar usuário\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
        await testRunner.ThenAsync("devo visualizar a tela de recuperação de usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Recuperação de usuário sem informar credenciais")]
        [global::NUnit.Framework.CategoryAttribute("RecuperarUsuario")]
        public async global::System.Threading.Tasks.Task RecuperacaoDeUsuarioSemInformarCredenciais()
        {
            string[] tagsOfScenario = new string[] {
                    "RecuperarUsuario"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Recuperação de usuário sem informar credenciais", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 40
        await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
        await testRunner.AndAsync("clico em \"Recuperar usuário\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
        await testRunner.ThenAsync("devo visualizar uma mensagem de erro solicitando o preenchimento do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Fluxo de redefinição de senha")]
        [global::NUnit.Framework.CategoryAttribute("RedefinirSenha")]
        public async global::System.Threading.Tasks.Task FluxoDeRedefinicaoDeSenha()
        {
            string[] tagsOfScenario = new string[] {
                    "RedefinirSenha"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fluxo de redefinição de senha", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 47
      await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
      await testRunner.AndAsync("preencho o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
      await testRunner.AndAsync("clico em \"Redefinir senha\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
      await testRunner.ThenAsync("devo visualizar a tela de redefinição de senha", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Redefinição de senha sem informar credenciais")]
        [global::NUnit.Framework.CategoryAttribute("RedefinirSenha")]
        public async global::System.Threading.Tasks.Task RedefinicaoDeSenhaSemInformarCredenciais()
        {
            string[] tagsOfScenario = new string[] {
                    "RedefinirSenha"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Redefinição de senha sem informar credenciais", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 54
      await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
      await testRunner.AndAsync("clico em \"Redefinir senha\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
      await testRunner.ThenAsync("devo visualizar uma mensagem de erro solicitando a identificação do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tentativa de acesso direto sem login")]
        [global::NUnit.Framework.CategoryAttribute("Seguranca")]
        public async global::System.Threading.Tasks.Task TentativaDeAcessoDiretoSemLogin()
        {
            string[] tagsOfScenario = new string[] {
                    "Seguranca"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentativa de acesso direto sem login", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
      this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 62
        await testRunner.GivenAsync("que acesso diretamente a URL da área do candidato sem estar autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
        await testRunner.ThenAsync("devo ser redirecionado para a tela de login", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
