// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ChallengeQa.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Login do candidato")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class LoginDoCandidatoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Login do candidato", "  Como candidato\r\n  Quero acessar a área do candidato\r\n  Para visualizar minhas i" +
                "nformações após o cadastro", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Login.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
  await testRunner.GivenAsync("que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                    "re\" do nível \"Pós-graduação\" recebendo credenciais válidas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Login.feature", "Feature: Login do candidato\r\n  Como candidato\r\n  Quero acessar a área do candidat" +
                    "o\r\n  Para visualizar minhas informações após o cadastro\r\n\r\nBackground:\r\n  Given " +
                    "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softw" +
                    "are\" do nível \"Pós-graduação\" recebendo credenciais válidas\r\n\r\n    @Login @GT-00" +
                    "7\r\n    Scenario: Login com credenciais geradas no cadastro\r\n        When acesso " +
                    "a área do candidato\r\n        And preencho o usuário e senha válidos\r\n        And" +
                    " clico em \"Login\"\r\n        Then devo visualizar a página inicial da área do cand" +
                    "idato\r\n\r\n    @LoginInvalido @GT-008\r\n    Scenario Outline: Tentativa de login in" +
                    "válido\r\n        When acesso a área do candidato\r\n        And preencho usuário \"<" +
                    "usuario>\" e senha \"<senha>\"\r\n        And clico em \"Login\"\r\n        Then devo vis" +
                    "ualizar a mensagem de erro <campo> \"<mensagem>\"\r\n\r\n    Examples:\r\n        | usua" +
                    "rio         | senha             | campo    | mensagem          |\r\n        | usua" +
                    "rioInvalido | subscription      | usuário  | Usuário inválido  |\r\n        | cand" +
                    "idato       | Senha_inválida    | senha    | Senha inválida    |\r\n        | usua" +
                    "rioInvalido | Senha_inválida    | usuário  | Usuário inválido  |\r\n        | usua" +
                    "rioInvalido | Senha_inválida    | senha    | Senha inválida    |\r\n\r\n\r\n    @Recup" +
                    "erarUsuario @GT-009\r\n    Scenario: Fluxo de recuperação de usuário\r\n        When" +
                    " acesso a área do candidato\r\n        And preencho o usuário\r\n        And clico e" +
                    "m \"Recuperar usuário\"\r\n        Then devo visualizar a tela de recuperação de usu" +
                    "ário\r\n\r\n    @RecuperarUsuario @GT-010\r\n    Scenario: Recuperação de usuário sem " +
                    "informar credenciais\r\n        When acesso a área do candidato\r\n        And clico" +
                    " em \"Recuperar usuário\"\r\n        Then devo visualizar uma mensagem de erro solic" +
                    "itando o preenchimento do usuário\r\n\r\n\r\n    @RedefinirSenha @GT-011\r\n    Scenario" +
                    ": Fluxo de redefinição de senha\r\n      When acesso a área do candidato\r\n      An" +
                    "d preencho o usuário\r\n      And clico em \"Redefinir senha\"\r\n      Then devo visu" +
                    "alizar a tela de redefinição de senha\r\n\r\n    @RedefinirSenha @GT-012\r\n    Scenar" +
                    "io: Redefinição de senha sem informar credenciais\r\n      When acesso a área do c" +
                    "andidato\r\n      And clico em \"Redefinir senha\"\r\n      Then devo visualizar uma m" +
                    "ensagem de erro solicitando a identificação do usuário\r\n\r\n\r\n\r\n      @Seguranca @" +
                    "GT-013\r\n      Scenario: Tentativa de acesso direto sem login\r\n        Given que " +
                    "acesso diretamente a URL da área do candidato sem estar autenticado\r\n        The" +
                    "n devo ser redirecionado para a tela de login\r\n\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Login.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Login do candidato", "  Como candidato\r\n  Quero acessar a área do candidato\r\n  Para visualizar minhas i" +
                        "nformações após o cadastro", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(1)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(3)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                            "re\" do nível \"Pós-graduação\" recebendo credenciais válidas", null, null, "c340baf8e1f77a5aa3ed5840ffc49227")}), "a8a8f49005a87c5c80aee7b8a68cfb86"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "@Login", "639fa90012aec85c90a8e1fa71bc6442"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(12)), "@GT-007", "ff790e1eff14025c8d0c96084c9f8a17")}), "Scenario", "Login com credenciais geradas no cadastro", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(9)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "345a31b4d1c4b5519f2f8a509a47f399"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "preencho o usuário e senha válidos", null, null, "4564d4aa38b9395a8a2f4b15d05bbb4a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Login\"", null, null, "f404d8a59d12c3558d8b9c0571a6d126"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar a página inicial da área do candidato", null, null, "18f1c48092ae89548fe4491837bbdf0a")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "ebf19049fa9e3354bdb609e206330e21")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "@LoginInvalido", "01b2719d6483745ea2a48fc961d8288a"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(20)), "@GT-008", "5868d3951ce75a53982df5888f5dd0f5")}), "Scenario Outline", "Tentativa de login inválido", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(9)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "3842e038d6624b598e5a25e9129e734d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "preencho usuário \"<usuario>\" e senha \"<senha>\"", null, null, "3089f8b2a94ab85ab9503f78efce2b68"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Login\"", null, null, "5d73df605b943853990c7cad04f49c56"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar a mensagem de erro <campo> \"<mensagem>\"", null, null, "3be4b488e5bfe9519720dea4d7a498b7")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(9)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(11)), "usuario"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(29)), "senha"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(49)), "campo"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(60)), "mensagem")}), "6e6ef3b944fff55ebf182fb92a978a8b"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(9)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(11)), "usuarioInvalido"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(29)), "subscription"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(49)), "usuário"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(60)), "Usuário inválido")}), "b40cb6db9b3dec52b2e81efe8810dfeb"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(9)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(11)), "candidato"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(29)), "Senha_inválida"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(49)), "senha"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(60)), "Senha inválida")}), "a1634fa1682ff75084dd9bbb66117437"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(9)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(11)), "usuarioInvalido"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(29)), "Senha_inválida"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(49)), "usuário"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(60)), "Usuário inválido")}), "1c9533a4f1355f52a9f85979d1684bd6"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(9)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(11)), "usuarioInvalido"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(29)), "Senha_inválida"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(49)), "senha"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(60)), "Senha inválida")}), "2af5827488fa685b955db74f98217f2c")}), "6ff15d9b7d73b95a9217e0664a7eb097")}), "5bc6de8a83e7435db208b269a352c5d8")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "@RecuperarUsuario", "ce5be689efc2b656bc597cd51b0a0cf5"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(23)), "@GT-009", "1b4647541f9b4356bf66fd7c45e0161f")}), "Scenario", "Fluxo de recuperação de usuário", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(9)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "2b89c08b0848715a9a4510efc4c07404"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "preencho o usuário", null, null, "201d3ca26985d0569514d1657b4ebea2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Recuperar usuário\"", null, null, "1e8bc446ae2fdc52b4f4d2a34b368ccb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar a tela de recuperação de usuário", null, null, "d2dfdb7a51163557ae65d303d23b4e2f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "2af24b9b8ff81553ba3c146ce0044132")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "@RecuperarUsuario", "33220f481d643a58b33cc1da89f9383a"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(23)), "@GT-010", "3be99223837e29509b68643ddc8658dc")}), "Scenario", "Recuperação de usuário sem informar credenciais", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(9)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "bcfb815d1afd3a578baf1464e20ca96a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(9)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Recuperar usuário\"", null, null, "d74772265386a55baf6ebc58ec25465f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar uma mensagem de erro solicitando o preenchimento do usuário", null, null, "a428f54b56ead25082e74c13129c02b1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "b38f96ea5a3f185bad86709c701826f2")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(5)), "@RedefinirSenha", "adeb7ea8f1f37b50850a8d2410da09d0"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(21)), "@GT-011", "639c246b9196b259a510009c2802cff6")}), "Scenario", "Fluxo de redefinição de senha", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(7)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "0d21ecb620198556b935a6ad7b7a92fc"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(7)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "preencho o usuário", null, null, "0edb01d877e0da5b8c6d4c8f6578b353"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(7)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Redefinir senha\"", null, null, "f2edfd821ea21d5a8297f2e65c18d940"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(7)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar a tela de redefinição de senha", null, null, "e1224f4b9e4e165db4d3995f61916d9c")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e5663f6ed987b350b27dbe36836a5fa0")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(53, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(5)), "@RedefinirSenha", "e2ff95230370135ab1bb26bc18160ce1"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(21)), "@GT-012", "d46ccc6f602d345ca7b6f5acf636cdc4")}), "Scenario", "Redefinição de senha sem informar credenciais", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(7)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "acesso a área do candidato", null, null, "2c1f90544e20455f8de5b3a0bae301c1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(7)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Redefinir senha\"", null, null, "cebcd2ba7071ce5f9a24f461da2b2934"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(7)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar uma mensagem de erro solicitando a identificação do usuário", null, null, "8aa510b93eba845c8761dcec4b6e8921")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "3c3a4e05d72f19569cac28f9e14e5ce2")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(60, new System.Nullable<long>(7)), "@Seguranca", "ac838f64a523005ab199e53844216366"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(60, new System.Nullable<long>(18)), "@GT-013", "848150d9e628985c8f3776932c0f3d1f")}), "Scenario", "Tentativa de acesso direto sem login", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(62, new System.Nullable<long>(9)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que acesso diretamente a URL da área do candidato sem estar autenticado", null, null, "ef20cb1bc475fa569cee06524bedc3a3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(63, new System.Nullable<long>(9)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo ser redirecionado para a tela de login", null, null, "ec1dd1bcdd7f5a589c233cfdce4f505a")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "5f90586f548ef756893d1d496a78fd87"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("5d5858a9c7bef651887acb9b8a955ea7", "Features/Login.feature", "Login com credenciais geradas no cadastro", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c340baf8e1f77a5aa3ed5840ffc49227"}), "22e524756a69e457884507bb2b0f9197", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "345a31b4d1c4b5519f2f8a509a47f399"}), "038230aef5ffe35ca78e6022dd1901b5", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4564d4aa38b9395a8a2f4b15d05bbb4a"}), "26ad7783b37ea054a535eebf1898cc87", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário e senha válidos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f404d8a59d12c3558d8b9c0571a6d126"}), "55c85f4c6a574554869589afc62ac2c0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "18f1c48092ae89548fe4491837bbdf0a"}), "204a5fe16bccd154b4ef73a8b4cfc4b0", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a página inicial da área do candidato")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "639fa90012aec85c90a8e1fa71bc6442"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-007", "ff790e1eff14025c8d0c96084c9f8a17")}), new System.Collections.Generic.List<string>(new string[] {
                                        "ebf19049fa9e3354bdb609e206330e21"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("b599d1eba665e95085f436cd54393281", "Features/Login.feature", "Tentativa de login inválido", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c340baf8e1f77a5aa3ed5840ffc49227"}), "2ccbd38a514c76528c299d27e8ca4d03", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3842e038d6624b598e5a25e9129e734d",
                                                        "b40cb6db9b3dec52b2e81efe8810dfeb"}), "e3d3176435316c5d9a8a5109235f932e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3089f8b2a94ab85ab9503f78efce2b68",
                                                        "b40cb6db9b3dec52b2e81efe8810dfeb"}), "32b00afde839a854bf13b0b6274fc2db", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho usuário \"usuarioInvalido\" e senha \"subscription\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5d73df605b943853990c7cad04f49c56",
                                                        "b40cb6db9b3dec52b2e81efe8810dfeb"}), "2abd5eab8e721353b3a56aeb6eba9eba", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3be4b488e5bfe9519720dea4d7a498b7",
                                                        "b40cb6db9b3dec52b2e81efe8810dfeb"}), "16418835d8e2685a8ac12e64dea6ce91", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a mensagem de erro usuário \"Usuário inválido\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@LoginInvalido", "01b2719d6483745ea2a48fc961d8288a"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-008", "5868d3951ce75a53982df5888f5dd0f5")}), new System.Collections.Generic.List<string>(new string[] {
                                        "5bc6de8a83e7435db208b269a352c5d8",
                                        "b40cb6db9b3dec52b2e81efe8810dfeb"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("357577aef80d885db3d97d8e3e04b9aa", "Features/Login.feature", "Tentativa de login inválido", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c340baf8e1f77a5aa3ed5840ffc49227"}), "92e99687ac204a539186b4d27ddb345a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3842e038d6624b598e5a25e9129e734d",
                                                        "a1634fa1682ff75084dd9bbb66117437"}), "fdf1f82ad293c85f82eec5aed1aedbad", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3089f8b2a94ab85ab9503f78efce2b68",
                                                        "a1634fa1682ff75084dd9bbb66117437"}), "dbe97f2fab27565199c126e60dadd8dd", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho usuário \"candidato\" e senha \"Senha_inválida\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5d73df605b943853990c7cad04f49c56",
                                                        "a1634fa1682ff75084dd9bbb66117437"}), "91f7c5d3aefe2e50826ebfd879a6792c", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3be4b488e5bfe9519720dea4d7a498b7",
                                                        "a1634fa1682ff75084dd9bbb66117437"}), "8c474c7abe74995489a4c1879a7fd9a1", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a mensagem de erro senha \"Senha inválida\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@LoginInvalido", "01b2719d6483745ea2a48fc961d8288a"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-008", "5868d3951ce75a53982df5888f5dd0f5")}), new System.Collections.Generic.List<string>(new string[] {
                                        "5bc6de8a83e7435db208b269a352c5d8",
                                        "a1634fa1682ff75084dd9bbb66117437"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("5c7568a327ef0059baa57aa1f68c287b", "Features/Login.feature", "Tentativa de login inválido", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c340baf8e1f77a5aa3ed5840ffc49227"}), "0e16952af6819758b53c1bfeebda9428", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3842e038d6624b598e5a25e9129e734d",
                                                        "1c9533a4f1355f52a9f85979d1684bd6"}), "f231165361df715f854825a9a707f704", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3089f8b2a94ab85ab9503f78efce2b68",
                                                        "1c9533a4f1355f52a9f85979d1684bd6"}), "2b2bb3bf5138f55cbccc7acc3f4be74f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho usuário \"usuarioInvalido\" e senha \"Senha_inválida\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5d73df605b943853990c7cad04f49c56",
                                                        "1c9533a4f1355f52a9f85979d1684bd6"}), "c9cd73824529c75f805ebfe6343b4fd0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3be4b488e5bfe9519720dea4d7a498b7",
                                                        "1c9533a4f1355f52a9f85979d1684bd6"}), "3b01d0c9af51715682ae43a41e1a9704", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a mensagem de erro usuário \"Usuário inválido\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@LoginInvalido", "01b2719d6483745ea2a48fc961d8288a"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-008", "5868d3951ce75a53982df5888f5dd0f5")}), new System.Collections.Generic.List<string>(new string[] {
                                        "5bc6de8a83e7435db208b269a352c5d8",
                                        "1c9533a4f1355f52a9f85979d1684bd6"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("15a7160195117f5c9e3501d6fbfc8707", "Features/Login.feature", "Tentativa de login inválido", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c340baf8e1f77a5aa3ed5840ffc49227"}), "0178d2493648855abb5e505a64df20b5", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3842e038d6624b598e5a25e9129e734d",
                                                        "2af5827488fa685b955db74f98217f2c"}), "055477c344c0e25a9ad15df75d967a2a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3089f8b2a94ab85ab9503f78efce2b68",
                                                        "2af5827488fa685b955db74f98217f2c"}), "49c2dc61a531fa52889cd1273a25daac", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho usuário \"usuarioInvalido\" e senha \"Senha_inválida\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5d73df605b943853990c7cad04f49c56",
                                                        "2af5827488fa685b955db74f98217f2c"}), "5d0f6f488e361d5cbfe2e735eab55ee7", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3be4b488e5bfe9519720dea4d7a498b7",
                                                        "2af5827488fa685b955db74f98217f2c"}), "ce018e8dc685f85289a185198fe9e9d4", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a mensagem de erro senha \"Senha inválida\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@LoginInvalido", "01b2719d6483745ea2a48fc961d8288a"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-008", "5868d3951ce75a53982df5888f5dd0f5")}), new System.Collections.Generic.List<string>(new string[] {
                                        "5bc6de8a83e7435db208b269a352c5d8",
                                        "2af5827488fa685b955db74f98217f2c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("469f569ead9d65539998ff9dc4f75914", "Features/Login.feature", "Fluxo de recuperação de usuário", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c340baf8e1f77a5aa3ed5840ffc49227"}), "548475e1f986ef51a8e4465da3b87e10", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2b89c08b0848715a9a4510efc4c07404"}), "9738786bcc2a7f5a9fffc8a173b88eef", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "201d3ca26985d0569514d1657b4ebea2"}), "4c984eaead23955584b8a34d0190f98e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1e8bc446ae2fdc52b4f4d2a34b368ccb"}), "f8c86c8bd0215f5a933f11fe5059f177", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Recuperar usuário\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d2dfdb7a51163557ae65d303d23b4e2f"}), "259c5cfc4fc5805c99ddb9e8fdf72cba", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a tela de recuperação de usuário")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@RecuperarUsuario", "ce5be689efc2b656bc597cd51b0a0cf5"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-009", "1b4647541f9b4356bf66fd7c45e0161f")}), new System.Collections.Generic.List<string>(new string[] {
                                        "2af24b9b8ff81553ba3c146ce0044132"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("25c9025ab7adcb52951cb53772c12016", "Features/Login.feature", "Recuperação de usuário sem informar credenciais", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c340baf8e1f77a5aa3ed5840ffc49227"}), "e93edb846eb75e5c99a5c49d90c98c4c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bcfb815d1afd3a578baf1464e20ca96a"}), "9ea035ee8046c056ad571d5204945724", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d74772265386a55baf6ebc58ec25465f"}), "45ace6faf1196a5a8ffc94527c0291c1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Recuperar usuário\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a428f54b56ead25082e74c13129c02b1"}), "16c9e3ae8e56265fb9f6c458c05a0749", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar uma mensagem de erro solicitando o preenchimento do usuário")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@RecuperarUsuario", "33220f481d643a58b33cc1da89f9383a"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-010", "3be99223837e29509b68643ddc8658dc")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b38f96ea5a3f185bad86709c701826f2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("784dcdeced30675a9eb3186cd4207bf5", "Features/Login.feature", "Fluxo de redefinição de senha", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c340baf8e1f77a5aa3ed5840ffc49227"}), "ad9e527636c80c508096701fb9d3e06a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0d21ecb620198556b935a6ad7b7a92fc"}), "bfcc1dff90a80359b6347c985a2343d9", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0edb01d877e0da5b8c6d4c8f6578b353"}), "3d6ce23b952af85cacdcf070761231b1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f2edfd821ea21d5a8297f2e65c18d940"}), "5e1ff9f31e38555eb09e5ace742f6720", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Redefinir senha\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e1224f4b9e4e165db4d3995f61916d9c"}), "ab8943cd787258529f8257cbebc44e7b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a tela de redefinição de senha")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@RedefinirSenha", "adeb7ea8f1f37b50850a8d2410da09d0"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-011", "639c246b9196b259a510009c2802cff6")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e5663f6ed987b350b27dbe36836a5fa0"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f89bb4d064abe25482bedad4673f7be1", "Features/Login.feature", "Redefinição de senha sem informar credenciais", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c340baf8e1f77a5aa3ed5840ffc49227"}), "a7687cc1856fe55192cc0209b0fa1eff", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2c1f90544e20455f8de5b3a0bae301c1"}), "f43d93792abd4357a336e6f56c5d352d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "acesso a área do candidato"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cebcd2ba7071ce5f9a24f461da2b2934"}), "3940248c23e77a5f93cf6625c958e0f9", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Redefinir senha\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8aa510b93eba845c8761dcec4b6e8921"}), "303179b4526e79588ff18b61fc9a21ca", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar uma mensagem de erro solicitando a identificação do usuário")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@RedefinirSenha", "e2ff95230370135ab1bb26bc18160ce1"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-012", "d46ccc6f602d345ca7b6f5acf636cdc4")}), new System.Collections.Generic.List<string>(new string[] {
                                        "3c3a4e05d72f19569cac28f9e14e5ce2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("e79c70bf22bde256a5af11d97e2096a9", "Features/Login.feature", "Tentativa de acesso direto sem login", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c340baf8e1f77a5aa3ed5840ffc49227"}), "a438281041a59850beb5b3051a2e1f81", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que concluo o cadastro de um candidato no curso \"Mestrado em Engenharia de Softwa" +
                                                "re\" do nível \"Pós-graduação\" recebendo credenciais válidas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ef20cb1bc475fa569cee06524bedc3a3"}), "e4510a4756e1ce56a6f40d45380c7737", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso diretamente a URL da área do candidato sem estar autenticado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ec1dd1bcdd7f5a589c233cfdce4f505a"}), "a5b6913354d47c57a0804111b2b9b6b7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo ser redirecionado para a tela de login")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Seguranca", "ac838f64a523005ab199e53844216366"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-013", "848150d9e628985c8f3776932c0f3d1f")}), new System.Collections.Generic.List<string>(new string[] {
                                        "5f90586f548ef756893d1d496a78fd87"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(LoginDoCandidatoFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(LoginDoCandidatoFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(LoginDoCandidatoFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Login com credenciais geradas no cadastro")]
        [global::NUnit.Framework.CategoryAttribute("Login")]
        [global::NUnit.Framework.CategoryAttribute("GT-007")]
        public async global::System.Threading.Tasks.Task LoginComCredenciaisGeradasNoCadastro()
        {
            string[] tagsOfScenario = new string[] {
                    "Login",
                    "GT-007"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login com credenciais geradas no cadastro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 11
        await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
        await testRunner.AndAsync("preencho o usuário e senha válidos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
        await testRunner.AndAsync("clico em \"Login\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
        await testRunner.ThenAsync("devo visualizar a página inicial da área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tentativa de login inválido")]
        [global::NUnit.Framework.CategoryAttribute("LoginInvalido")]
        [global::NUnit.Framework.CategoryAttribute("GT-008")]
        [global::NUnit.Framework.TestCaseAttribute("usuarioInvalido", "subscription", "usuário", "Usuário inválido", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("candidato", "Senha_inválida", "senha", "Senha inválida", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("usuarioInvalido", "Senha_inválida", "usuário", "Usuário inválido", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("usuarioInvalido", "Senha_inválida", "senha", "Senha inválida", "4", null)]
        public async global::System.Threading.Tasks.Task TentativaDeLoginInvalido(string usuario, string senha, string campo, string mensagem, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "LoginInvalido",
                    "GT-008"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("usuario", usuario);
            argumentsOfScenario.Add("senha", senha);
            argumentsOfScenario.Add("campo", campo);
            argumentsOfScenario.Add("mensagem", mensagem);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentativa de login inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 18
        await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
        await testRunner.AndAsync(string.Format("preencho usuário \"{0}\" e senha \"{1}\"", usuario, senha), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
        await testRunner.AndAsync("clico em \"Login\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
        await testRunner.ThenAsync(string.Format("devo visualizar a mensagem de erro {0} \"{1}\"", campo, mensagem), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Fluxo de recuperação de usuário")]
        [global::NUnit.Framework.CategoryAttribute("RecuperarUsuario")]
        [global::NUnit.Framework.CategoryAttribute("GT-009")]
        public async global::System.Threading.Tasks.Task FluxoDeRecuperacaoDeUsuario()
        {
            string[] tagsOfScenario = new string[] {
                    "RecuperarUsuario",
                    "GT-009"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fluxo de recuperação de usuário", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 33
        await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
        await testRunner.AndAsync("preencho o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
        await testRunner.AndAsync("clico em \"Recuperar usuário\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
        await testRunner.ThenAsync("devo visualizar a tela de recuperação de usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Recuperação de usuário sem informar credenciais")]
        [global::NUnit.Framework.CategoryAttribute("RecuperarUsuario")]
        [global::NUnit.Framework.CategoryAttribute("GT-010")]
        public async global::System.Threading.Tasks.Task RecuperacaoDeUsuarioSemInformarCredenciais()
        {
            string[] tagsOfScenario = new string[] {
                    "RecuperarUsuario",
                    "GT-010"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Recuperação de usuário sem informar credenciais", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 40
        await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
        await testRunner.AndAsync("clico em \"Recuperar usuário\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
        await testRunner.ThenAsync("devo visualizar uma mensagem de erro solicitando o preenchimento do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Fluxo de redefinição de senha")]
        [global::NUnit.Framework.CategoryAttribute("RedefinirSenha")]
        [global::NUnit.Framework.CategoryAttribute("GT-011")]
        public async global::System.Threading.Tasks.Task FluxoDeRedefinicaoDeSenha()
        {
            string[] tagsOfScenario = new string[] {
                    "RedefinirSenha",
                    "GT-011"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fluxo de redefinição de senha", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 47
      await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
      await testRunner.AndAsync("preencho o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
      await testRunner.AndAsync("clico em \"Redefinir senha\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
      await testRunner.ThenAsync("devo visualizar a tela de redefinição de senha", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Redefinição de senha sem informar credenciais")]
        [global::NUnit.Framework.CategoryAttribute("RedefinirSenha")]
        [global::NUnit.Framework.CategoryAttribute("GT-012")]
        public async global::System.Threading.Tasks.Task RedefinicaoDeSenhaSemInformarCredenciais()
        {
            string[] tagsOfScenario = new string[] {
                    "RedefinirSenha",
                    "GT-012"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Redefinição de senha sem informar credenciais", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 54
      await testRunner.WhenAsync("acesso a área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
      await testRunner.AndAsync("clico em \"Redefinir senha\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
      await testRunner.ThenAsync("devo visualizar uma mensagem de erro solicitando a identificação do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tentativa de acesso direto sem login")]
        [global::NUnit.Framework.CategoryAttribute("Seguranca")]
        [global::NUnit.Framework.CategoryAttribute("GT-013")]
        public async global::System.Threading.Tasks.Task TentativaDeAcessoDiretoSemLogin()
        {
            string[] tagsOfScenario = new string[] {
                    "Seguranca",
                    "GT-013"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentativa de acesso direto sem login", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
      this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 62
        await testRunner.GivenAsync("que acesso diretamente a URL da área do candidato sem estar autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
        await testRunner.ThenAsync("devo ser redirecionado para a tela de login", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
