// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ChallengeQa.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Política de Privacidade")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class PoliticaDePrivacidadeFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Política de Privacidade", "  Como usuário\r\n  Quero acessar a página de Política de Privacidade\r\n  Para enten" +
                "der como meus dados são tratados", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Pribacy.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Pribacy.feature", @"Feature: Política de Privacidade
  Como usuário
  Quero acessar a página de Política de Privacidade
  Para entender como meus dados são tratados

  @PrivacyPolicy @GT-014
  Scenario: Validar a página de Política de Privacidade no Chrome
    Given que acesso a página ""https://developer.grupoa.education/subscription/"" no chrome
    When clico no link ""Política de Privacidade""
    Then devo visualizar o título ""Política de Privacidade""

  @PrivacyPolicy @GT-015
  Scenario: Validar a página de Política de Privacidade no Firefox
    Given que acesso a página ""https://developer.grupoa.education/subscription/"" no firefox
    When clico no link ""Política de Privacidade""
    Then devo visualizar o título ""Política de Privacidade""

  @PrivacyPolicy @GT-016
  Scenario: Validar a página de Política de Privacidade no Edge
    Given que acesso a página ""https://developer.grupoa.education/subscription/"" no edge
    When clico no link ""Política de Privacidade""
    Then devo visualizar o título ""Política de Privacidade""
", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Pribacy.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Política de Privacidade", "  Como usuário\r\n  Quero acessar a página de Política de Privacidade\r\n  Para enten" +
                        "der como meus dados são tratados", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "@PrivacyPolicy", "85afc720ca61e25081c085aafe7b6d02"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(18)), "@GT-014", "8c0d1cbab2ae675889655e04720ce646")}), "Scenario", "Validar a página de Política de Privacidade no Chrome", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no chrome", null, null, "4fcc7f9ea61e5b5a87c0a2e0c774932c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "clico no link \"Política de Privacidade\"", null, null, "ef3a6b24ef8a715ba6906abc0ffe9aa9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"", null, null, "47c36e85d72ea556ac5c48e7bf6bc7bb")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "1ebc73f20bfe065b87e108a31cef7f72")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(3)), "@PrivacyPolicy", "40463c7156d1bc5d96532f71c4139c6a"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(18)), "@GT-015", "72b492d413002d538068cb4ba7a5d965")}), "Scenario", "Validar a página de Política de Privacidade no Firefox", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no firefox" +
                                                            "", null, null, "d78d71c57e01c45d8bba31daf4559c49"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "clico no link \"Política de Privacidade\"", null, null, "b8f223e824b32e5e8e680d6cf7400a11"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"", null, null, "c1315b5bfca8295aab456501662dd9cf")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "45a1fc56c4b6aa52b285cb1fa0075051")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(3)), "@PrivacyPolicy", "6f9642fa72e6f35492013918ebd6ae1e"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(18)), "@GT-016", "dc79f739f9951450befa017472553198")}), "Scenario", "Validar a página de Política de Privacidade no Edge", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no edge", null, null, "bb626257eb9b6250bedeca8a52800a5f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "clico no link \"Política de Privacidade\"", null, null, "6f4c413fc92577528753fa4ad8c03c5e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"", null, null, "c2e8b43e1dcd6852988a5f70b43a2a17")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "dc18c9767f284f57ab043f97c5e43ec0"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("7621dd58830250598b9c2fec24dbe2fa", "Features/Pribacy.feature", "Validar a página de Política de Privacidade no Chrome", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4fcc7f9ea61e5b5a87c0a2e0c774932c"}), "9ad7f83bb91c0d5c9c4778a3aba00615", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no chrome"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ef3a6b24ef8a715ba6906abc0ffe9aa9"}), "e54ce0f444e38b54a7be1b814781f210", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico no link \"Política de Privacidade\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "47c36e85d72ea556ac5c48e7bf6bc7bb"}), "f27abaacc9d61b52a4c5a983f3bb864d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@PrivacyPolicy", "85afc720ca61e25081c085aafe7b6d02"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-014", "8c0d1cbab2ae675889655e04720ce646")}), new System.Collections.Generic.List<string>(new string[] {
                                        "1ebc73f20bfe065b87e108a31cef7f72"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3710819a75d4325488314362a6737dc9", "Features/Pribacy.feature", "Validar a página de Política de Privacidade no Firefox", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d78d71c57e01c45d8bba31daf4559c49"}), "8ec423087c881b568a50d048684a92bf", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no firefox" +
                                                ""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b8f223e824b32e5e8e680d6cf7400a11"}), "ebdab04469cb3b56b3f8aa992c0bd5e7", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico no link \"Política de Privacidade\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c1315b5bfca8295aab456501662dd9cf"}), "9a1121b4682b1e5d8d95f79394dfb43a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@PrivacyPolicy", "40463c7156d1bc5d96532f71c4139c6a"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-015", "72b492d413002d538068cb4ba7a5d965")}), new System.Collections.Generic.List<string>(new string[] {
                                        "45a1fc56c4b6aa52b285cb1fa0075051"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("ce1e9cb84f4e2e549d4392e4bcaf54e6", "Features/Pribacy.feature", "Validar a página de Política de Privacidade no Edge", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bb626257eb9b6250bedeca8a52800a5f"}), "99aa22ef84164d57a8a085ee3d675940", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no edge"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6f4c413fc92577528753fa4ad8c03c5e"}), "575ebb6fba955d5d8d482fe00961fda9", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico no link \"Política de Privacidade\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c2e8b43e1dcd6852988a5f70b43a2a17"}), "d0d9666f73278e54b60a967398692caf", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@PrivacyPolicy", "6f9642fa72e6f35492013918ebd6ae1e"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-016", "dc79f739f9951450befa017472553198")}), new System.Collections.Generic.List<string>(new string[] {
                                        "dc18c9767f284f57ab043f97c5e43ec0"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(PoliticaDePrivacidadeFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(PoliticaDePrivacidadeFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(PoliticaDePrivacidadeFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validar a página de Política de Privacidade no Chrome")]
        [global::NUnit.Framework.CategoryAttribute("PrivacyPolicy")]
        [global::NUnit.Framework.CategoryAttribute("GT-014")]
        public async global::System.Threading.Tasks.Task ValidarAPaginaDePoliticaDePrivacidadeNoChrome()
        {
            string[] tagsOfScenario = new string[] {
                    "PrivacyPolicy",
                    "GT-014"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar a página de Política de Privacidade no Chrome", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que acesso a página \"https://developer.grupoa.education/subscription/\" no chrome", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.WhenAsync("clico no link \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.ThenAsync("devo visualizar o título \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validar a página de Política de Privacidade no Firefox")]
        [global::NUnit.Framework.CategoryAttribute("PrivacyPolicy")]
        [global::NUnit.Framework.CategoryAttribute("GT-015")]
        public async global::System.Threading.Tasks.Task ValidarAPaginaDePoliticaDePrivacidadeNoFirefox()
        {
            string[] tagsOfScenario = new string[] {
                    "PrivacyPolicy",
                    "GT-015"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar a página de Política de Privacidade no Firefox", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
    await testRunner.GivenAsync("que acesso a página \"https://developer.grupoa.education/subscription/\" no firefox" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
    await testRunner.WhenAsync("clico no link \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("devo visualizar o título \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validar a página de Política de Privacidade no Edge")]
        [global::NUnit.Framework.CategoryAttribute("PrivacyPolicy")]
        [global::NUnit.Framework.CategoryAttribute("GT-016")]
        public async global::System.Threading.Tasks.Task ValidarAPaginaDePoliticaDePrivacidadeNoEdge()
        {
            string[] tagsOfScenario = new string[] {
                    "PrivacyPolicy",
                    "GT-016"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar a página de Política de Privacidade no Edge", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("que acesso a página \"https://developer.grupoa.education/subscription/\" no edge", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
    await testRunner.WhenAsync("clico no link \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("devo visualizar o título \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
