// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ChallengeQa.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Política de Privacidade")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class PoliticaDePrivacidadeFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Política de Privacidade", "  Como usuário\r\n  Quero acessar a página de Política de Privacidade\r\n  Para enten" +
                "der como meus dados são tratados", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Pribacy.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Pribacy.feature", @"Feature: Política de Privacidade
  Como usuário
  Quero acessar a página de Política de Privacidade
  Para entender como meus dados são tratados

  @PrivacyPolicy
  Scenario: Validar a página de Política de Privacidade no Chrome
    Given que acesso a página ""https://developer.grupoa.education/subscription/"" no chrome
    When clico no link ""Política de Privacidade""
    Then devo visualizar o título ""Política de Privacidade""

  @PrivacyPolicy
  Scenario: Validar a página de Política de Privacidade no Firefox
    Given que acesso a página ""https://developer.grupoa.education/subscription/"" no firefox
    When clico no link ""Política de Privacidade""
    Then devo visualizar o título ""Política de Privacidade""

  @PrivacyPolicy
  Scenario: Validar a página de Política de Privacidade no Edge
    Given que acesso a página ""https://developer.grupoa.education/subscription/"" no edge
    When clico no link ""Política de Privacidade""
    Then devo visualizar o título ""Política de Privacidade""
", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Pribacy.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Política de Privacidade", "  Como usuário\r\n  Quero acessar a página de Política de Privacidade\r\n  Para enten" +
                        "der como meus dados são tratados", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "@PrivacyPolicy", "2f60576f0b1bde539840215882b36feb")}), "Scenario", "Validar a página de Política de Privacidade no Chrome", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no chrome", null, null, "119b1835fd0e0f519c5d08afd74574e2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "clico no link \"Política de Privacidade\"", null, null, "35846767126b375c9625667e24dbb7cc"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"", null, null, "1cbaf39c2c8f305da5637b44f31e708c")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "d3b556dccbf74758b04b84be8ec8a86a")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(3)), "@PrivacyPolicy", "97e1a4fd563ae25da5b302c78398f3a7")}), "Scenario", "Validar a página de Política de Privacidade no Firefox", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no firefox" +
                                                            "", null, null, "846427ccb0882a54b760ae00fc46cdb5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "clico no link \"Política de Privacidade\"", null, null, "ea8f88627155fc5b94cc262795f6f69b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"", null, null, "05da647fe5f0a759b4c0cecf826dc448")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "f93d48f5241c645d8d682ab2f9d2d738")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(3)), "@PrivacyPolicy", "8e724991a4e40b5aa76da74cf02bcddd")}), "Scenario", "Validar a página de Política de Privacidade no Edge", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no edge", null, null, "f35b9966989c8e579e5be75e6fe15791"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "clico no link \"Política de Privacidade\"", null, null, "af2e9b3142744a5bb8ded60046c9f7b8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"", null, null, "8f8c4327f98c7855933d650680b041d4")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "26e337ec716bf556840bf00ba8fedf8f"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("3175ba1b117cb756a5c4bf4f131fa412", "Features/Pribacy.feature", "Validar a página de Política de Privacidade no Chrome", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "119b1835fd0e0f519c5d08afd74574e2"}), "afeda78c11f4595a8fcc189a6978d426", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no chrome"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "35846767126b375c9625667e24dbb7cc"}), "8e8b601af83ea85c96fc22343cdcc21f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico no link \"Política de Privacidade\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1cbaf39c2c8f305da5637b44f31e708c"}), "f2fd99838865ec5bac6f9e73618ea882", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@PrivacyPolicy", "2f60576f0b1bde539840215882b36feb")}), new System.Collections.Generic.List<string>(new string[] {
                                        "d3b556dccbf74758b04b84be8ec8a86a"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("0db5b5b96bdd0a59ab1914cf8e0b0807", "Features/Pribacy.feature", "Validar a página de Política de Privacidade no Firefox", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "846427ccb0882a54b760ae00fc46cdb5"}), "3a0d4b9227ec21549d1cc8560f5ea2c3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no firefox" +
                                                ""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ea8f88627155fc5b94cc262795f6f69b"}), "872db53ca2704d5facc626252b825492", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico no link \"Política de Privacidade\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "05da647fe5f0a759b4c0cecf826dc448"}), "fe1c4b931ecd02518316d564d58ef1d3", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@PrivacyPolicy", "97e1a4fd563ae25da5b302c78398f3a7")}), new System.Collections.Generic.List<string>(new string[] {
                                        "f93d48f5241c645d8d682ab2f9d2d738"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a7710b3d4441195da464ae77d2956149", "Features/Pribacy.feature", "Validar a página de Política de Privacidade no Edge", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f35b9966989c8e579e5be75e6fe15791"}), "12b2a16c05f5f65b90902762d2f488dc", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página \"https://developer.grupoa.education/subscription/\" no edge"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "af2e9b3142744a5bb8ded60046c9f7b8"}), "e03f6f2ae6344d548390617f5a02dde4", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico no link \"Política de Privacidade\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8f8c4327f98c7855933d650680b041d4"}), "3b4f441e7739b55bafed6a470bdf0451", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar o título \"Política de Privacidade\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@PrivacyPolicy", "8e724991a4e40b5aa76da74cf02bcddd")}), new System.Collections.Generic.List<string>(new string[] {
                                        "26e337ec716bf556840bf00ba8fedf8f"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(PoliticaDePrivacidadeFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(PoliticaDePrivacidadeFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(PoliticaDePrivacidadeFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validar a página de Política de Privacidade no Chrome")]
        [global::NUnit.Framework.CategoryAttribute("PrivacyPolicy")]
        public async global::System.Threading.Tasks.Task ValidarAPaginaDePoliticaDePrivacidadeNoChrome()
        {
            string[] tagsOfScenario = new string[] {
                    "PrivacyPolicy"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar a página de Política de Privacidade no Chrome", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que acesso a página \"https://developer.grupoa.education/subscription/\" no chrome", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.WhenAsync("clico no link \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.ThenAsync("devo visualizar o título \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validar a página de Política de Privacidade no Firefox")]
        [global::NUnit.Framework.CategoryAttribute("PrivacyPolicy")]
        public async global::System.Threading.Tasks.Task ValidarAPaginaDePoliticaDePrivacidadeNoFirefox()
        {
            string[] tagsOfScenario = new string[] {
                    "PrivacyPolicy"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar a página de Política de Privacidade no Firefox", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
    await testRunner.GivenAsync("que acesso a página \"https://developer.grupoa.education/subscription/\" no firefox" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
    await testRunner.WhenAsync("clico no link \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("devo visualizar o título \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validar a página de Política de Privacidade no Edge")]
        [global::NUnit.Framework.CategoryAttribute("PrivacyPolicy")]
        public async global::System.Threading.Tasks.Task ValidarAPaginaDePoliticaDePrivacidadeNoEdge()
        {
            string[] tagsOfScenario = new string[] {
                    "PrivacyPolicy"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar a página de Política de Privacidade no Edge", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("que acesso a página \"https://developer.grupoa.education/subscription/\" no edge", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
    await testRunner.WhenAsync("clico no link \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("devo visualizar o título \"Política de Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
