// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ChallengeQa.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Testes de Responsividade")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class TestesDeResponsividadeFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Testes de Responsividade", "  Como usuário em diferentes dispositivos\r\n  Quero visualizar corretamente o botã" +
                "o \"Avançar\"\r\n  Para conseguir prosseguir no fluxo de inscrição", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Responsiveness.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Responsiveness.feature", @"Feature: Testes de Responsividade
  Como usuário em diferentes dispositivos
  Quero visualizar corretamente o botão ""Avançar""
  Para conseguir prosseguir no fluxo de inscrição


@Login @Responsividade @GT-017
Scenario Outline: Fluxo de login completo em <resolucao>
  Given que acesso a página inicial com cadastro concluído no curso ""<curso>"" do nível ""<nivel>""
  When defino a janela para ""<resolucao>""
  And preencho o usuário e senha válidos
  And clico em ""Login""
  Then devo visualizar a página inicial da área do candidato

Examples:
  | curso                           | nivel          | resolucao  |
  | Mestrado em Engenharia de Software | Pós-graduação | 1366x768   |
  | Direito                         | Graduação      | 1920x1080  |
  | Psicologia                      | Graduação      | 375x812    |


", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Responsiveness.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Testes de Responsividade", "  Como usuário em diferentes dispositivos\r\n  Quero visualizar corretamente o botã" +
                        "o \"Avançar\"\r\n  Para conseguir prosseguir no fluxo de inscrição", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(1)), "@Login", "6702ba2425d75a5697e2867a1257cb0a"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(8)), "@Responsividade", "802f0ad3e35c8f5d99864fcbfb6e8594"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(24)), "@GT-017", "9ffea58856e85a52ab22b2b2ccceab82")}), "Scenario Outline", "Fluxo de login completo em <resolucao>", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(3)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que acesso a página inicial com cadastro concluído no curso \"<curso>\" do nível \"<" +
                                                            "nivel>\"", null, null, "7b93b3460344835580b3e86bac259865"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(3)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "defino a janela para \"<resolucao>\"", null, null, "5c036f1f83788f57924ee7578934e033"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(3)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "preencho o usuário e senha válidos", null, null, "74f725f5487d885aa59bb48ed15aa622"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(3)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Login\"", null, null, "f5ee1e8687c3cb508c5828bbad11e86b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(3)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar a página inicial da área do candidato", null, null, "12e487904bded45891a95095884d1980")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "curso"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(39)), "nivel"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(56)), "resolucao")}), "e6ef99009c793455abdd50486952d5d6"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "Mestrado em Engenharia de Software"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(42)), "Pós-graduação"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(58)), "1366x768")}), "ca278fac72d58e51aaee0cda4cabb246"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "Direito"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(39)), "Graduação"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(56)), "1920x1080")}), "3755f1a86637355a9713b5acc5df0fc5"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Psicologia"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(39)), "Graduação"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(56)), "375x812")}), "bd1e3899cc1b08588d8fa7825a5f0412")}), "cf5ede2d7a54de578caefd5e39ac59c5")}), "f869972c2f59335fa33d9cd1c80a670e"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("8e335d2bb8edc45cb2792ee15b44eb2f", "Features/Responsiveness.feature", "Fluxo de login completo em 1366x768", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7b93b3460344835580b3e86bac259865",
                                                        "ca278fac72d58e51aaee0cda4cabb246"}), "8f28b3574ab7cf5d854716bee14e25b9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página inicial com cadastro concluído no curso \"Mestrado em Engenhar" +
                                                "ia de Software\" do nível \"Pós-graduação\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5c036f1f83788f57924ee7578934e033",
                                                        "ca278fac72d58e51aaee0cda4cabb246"}), "8461f3d15025eb56b468fec28eefc6ae", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "defino a janela para \"1366x768\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "74f725f5487d885aa59bb48ed15aa622",
                                                        "ca278fac72d58e51aaee0cda4cabb246"}), "44247897bb9f135ab31fb86843a25a9b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário e senha válidos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f5ee1e8687c3cb508c5828bbad11e86b",
                                                        "ca278fac72d58e51aaee0cda4cabb246"}), "fa73ad47ce174750bda6630d19a74f01", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "12e487904bded45891a95095884d1980",
                                                        "ca278fac72d58e51aaee0cda4cabb246"}), "d2cd9d4d3b5eba588cf4f5336b8a43b5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a página inicial da área do candidato")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "6702ba2425d75a5697e2867a1257cb0a"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Responsividade", "802f0ad3e35c8f5d99864fcbfb6e8594"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-017", "9ffea58856e85a52ab22b2b2ccceab82")}), new System.Collections.Generic.List<string>(new string[] {
                                        "f869972c2f59335fa33d9cd1c80a670e",
                                        "ca278fac72d58e51aaee0cda4cabb246"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("fb0c01142334495b82bde3e19b46fce9", "Features/Responsiveness.feature", "Fluxo de login completo em 1920x1080", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7b93b3460344835580b3e86bac259865",
                                                        "3755f1a86637355a9713b5acc5df0fc5"}), "15e5d0a4b8b319598da8be324280b6ed", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página inicial com cadastro concluído no curso \"Direito\" do nível \"G" +
                                                "raduação\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5c036f1f83788f57924ee7578934e033",
                                                        "3755f1a86637355a9713b5acc5df0fc5"}), "fcd2de4a8b656c5a9cdc0a6f881b1f76", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "defino a janela para \"1920x1080\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "74f725f5487d885aa59bb48ed15aa622",
                                                        "3755f1a86637355a9713b5acc5df0fc5"}), "87a257a75c758b5d945199a88a3160ff", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário e senha válidos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f5ee1e8687c3cb508c5828bbad11e86b",
                                                        "3755f1a86637355a9713b5acc5df0fc5"}), "80ea5eebdf7afe5bbfa728f9c25580a3", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "12e487904bded45891a95095884d1980",
                                                        "3755f1a86637355a9713b5acc5df0fc5"}), "7fc4682c687dc9569640e9659a86743a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a página inicial da área do candidato")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "6702ba2425d75a5697e2867a1257cb0a"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Responsividade", "802f0ad3e35c8f5d99864fcbfb6e8594"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-017", "9ffea58856e85a52ab22b2b2ccceab82")}), new System.Collections.Generic.List<string>(new string[] {
                                        "f869972c2f59335fa33d9cd1c80a670e",
                                        "3755f1a86637355a9713b5acc5df0fc5"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("ff40334014618050828ea10d7d79fb3e", "Features/Responsiveness.feature", "Fluxo de login completo em 375x812", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7b93b3460344835580b3e86bac259865",
                                                        "bd1e3899cc1b08588d8fa7825a5f0412"}), "a7be28e666e85b5b928ee3aed155171d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página inicial com cadastro concluído no curso \"Psicologia\" do nível" +
                                                " \"Graduação\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5c036f1f83788f57924ee7578934e033",
                                                        "bd1e3899cc1b08588d8fa7825a5f0412"}), "5831f16378a96b5a82a211b364a10b28", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "defino a janela para \"375x812\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "74f725f5487d885aa59bb48ed15aa622",
                                                        "bd1e3899cc1b08588d8fa7825a5f0412"}), "acf4983374f8e653bbf6592b954a36c8", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário e senha válidos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f5ee1e8687c3cb508c5828bbad11e86b",
                                                        "bd1e3899cc1b08588d8fa7825a5f0412"}), "ddf18bffa2432756b02c31e268ab3901", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "12e487904bded45891a95095884d1980",
                                                        "bd1e3899cc1b08588d8fa7825a5f0412"}), "cca868eb5dcdb85b9e19baf509557a5b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a página inicial da área do candidato")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "6702ba2425d75a5697e2867a1257cb0a"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Responsividade", "802f0ad3e35c8f5d99864fcbfb6e8594"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@GT-017", "9ffea58856e85a52ab22b2b2ccceab82")}), new System.Collections.Generic.List<string>(new string[] {
                                        "f869972c2f59335fa33d9cd1c80a670e",
                                        "bd1e3899cc1b08588d8fa7825a5f0412"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(TestesDeResponsividadeFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(TestesDeResponsividadeFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(TestesDeResponsividadeFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Fluxo de login completo em <resolucao>")]
        [global::NUnit.Framework.CategoryAttribute("Login")]
        [global::NUnit.Framework.CategoryAttribute("Responsividade")]
        [global::NUnit.Framework.CategoryAttribute("GT-017")]
        [global::NUnit.Framework.TestCaseAttribute("Mestrado em Engenharia de Software", "Pós-graduação", "1366x768", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("Direito", "Graduação", "1920x1080", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("Psicologia", "Graduação", "375x812", "2", null)]
        public async global::System.Threading.Tasks.Task FluxoDeLoginCompletoEmResolucao(string curso, string nivel, string resolucao, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Login",
                    "Responsividade",
                    "GT-017"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("curso", curso);
            argumentsOfScenario.Add("nivel", nivel);
            argumentsOfScenario.Add("resolucao", resolucao);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fluxo de login completo em <resolucao>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await testRunner.GivenAsync(string.Format("que acesso a página inicial com cadastro concluído no curso \"{0}\" do nível \"{1}\"", curso, nivel), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
  await testRunner.WhenAsync(string.Format("defino a janela para \"{0}\"", resolucao), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
  await testRunner.AndAsync("preencho o usuário e senha válidos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
  await testRunner.AndAsync("clico em \"Login\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
  await testRunner.ThenAsync("devo visualizar a página inicial da área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
