// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ChallengeQa.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Testes de Responsividade")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class TestesDeResponsividadeFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Testes de Responsividade", "  Como usuário em diferentes dispositivos\r\n  Quero visualizar corretamente o botã" +
                "o \"Avançar\"\r\n  Para conseguir prosseguir no fluxo de inscrição", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Responsiveness.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Responsiveness.feature", @"Feature: Testes de Responsividade
  Como usuário em diferentes dispositivos
  Quero visualizar corretamente o botão ""Avançar""
  Para conseguir prosseguir no fluxo de inscrição


@Login @Responsividade
Scenario Outline: Fluxo de login completo em <resolucao>
  Given que acesso a página inicial com cadastro concluído no curso ""<curso>"" do nível ""<nivel>""
  When defino a janela para ""<resolucao>""
  And preencho o usuário e senha válidos
  And clico em ""Login""
  Then devo visualizar a página inicial da área do candidato

Examples:
  | curso                           | nivel          | resolucao  |
  | Mestrado em Engenharia de Software | Pós-graduação | 1366x768   |
  | Direito                         | Graduação      | 1920x1080  |
  | Psicologia                      | Graduação      | 375x812    |


", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Responsiveness.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Testes de Responsividade", "  Como usuário em diferentes dispositivos\r\n  Quero visualizar corretamente o botã" +
                        "o \"Avançar\"\r\n  Para conseguir prosseguir no fluxo de inscrição", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(1)), "@Login", "38c056d38fcc4050970283c59a19ae3d"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(8)), "@Responsividade", "50443eb82577045db52f85c35b0fd63f")}), "Scenario Outline", "Fluxo de login completo em <resolucao>", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(3)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "que acesso a página inicial com cadastro concluído no curso \"<curso>\" do nível \"<" +
                                                            "nivel>\"", null, null, "5fc6ff7928532d58878bdafe478dc465"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(3)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "defino a janela para \"<resolucao>\"", null, null, "0fd7ca5a3537245b859415fda0162549"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(3)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "preencho o usuário e senha válidos", null, null, "47bd32a1ff2f235aabbbd805383afd7d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(3)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "clico em \"Login\"", null, null, "c071d6451c6fb259b2585ba184fb7f24"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(3)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "devo visualizar a página inicial da área do candidato", null, null, "437a77a36d58465a8610689515b694b8")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "curso"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(39)), "nivel"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(56)), "resolucao")}), "aff62c321eefd75eb6dbf7962032f722"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "Mestrado em Engenharia de Software"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(42)), "Pós-graduação"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(58)), "1366x768")}), "548b9f945f372d54b673ce1094e39759"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "Direito"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(39)), "Graduação"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(56)), "1920x1080")}), "5d83b98a5787e352b92a61e0001737d0"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Psicologia"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(39)), "Graduação"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(56)), "375x812")}), "b265ce92066aec5db55297bc76abe21c")}), "6bea57d0370b9d5683d9a7cee583d048")}), "7468bfcc853dea57ac82c50d9228596f"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("fbf8f4938fe117599971e9e603a218f6", "Features/Responsiveness.feature", "Fluxo de login completo em 1366x768", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5fc6ff7928532d58878bdafe478dc465",
                                                        "548b9f945f372d54b673ce1094e39759"}), "9b4dda18cf9c1151a399b3adaaee5581", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página inicial com cadastro concluído no curso \"Mestrado em Engenhar" +
                                                "ia de Software\" do nível \"Pós-graduação\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0fd7ca5a3537245b859415fda0162549",
                                                        "548b9f945f372d54b673ce1094e39759"}), "c2ec9847d699fe54abd834380d3d0fbc", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "defino a janela para \"1366x768\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "47bd32a1ff2f235aabbbd805383afd7d",
                                                        "548b9f945f372d54b673ce1094e39759"}), "a249bf6024ebd659b36b1e665664e68a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário e senha válidos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c071d6451c6fb259b2585ba184fb7f24",
                                                        "548b9f945f372d54b673ce1094e39759"}), "0b2b12529313635393b1fe1af878647f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "437a77a36d58465a8610689515b694b8",
                                                        "548b9f945f372d54b673ce1094e39759"}), "518b4fb871fa06508133b49e3211f9f5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a página inicial da área do candidato")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "38c056d38fcc4050970283c59a19ae3d"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Responsividade", "50443eb82577045db52f85c35b0fd63f")}), new System.Collections.Generic.List<string>(new string[] {
                                        "7468bfcc853dea57ac82c50d9228596f",
                                        "548b9f945f372d54b673ce1094e39759"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("63dcd2bf93bcf25d81f2fabe57ec6b65", "Features/Responsiveness.feature", "Fluxo de login completo em 1920x1080", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5fc6ff7928532d58878bdafe478dc465",
                                                        "5d83b98a5787e352b92a61e0001737d0"}), "86f3cd34c66e47529104f9a03e95c0e6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página inicial com cadastro concluído no curso \"Direito\" do nível \"G" +
                                                "raduação\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0fd7ca5a3537245b859415fda0162549",
                                                        "5d83b98a5787e352b92a61e0001737d0"}), "efd191d71f269453b50b29225696a794", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "defino a janela para \"1920x1080\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "47bd32a1ff2f235aabbbd805383afd7d",
                                                        "5d83b98a5787e352b92a61e0001737d0"}), "b5c1c5a78efdee5e961cec1198993361", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário e senha válidos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c071d6451c6fb259b2585ba184fb7f24",
                                                        "5d83b98a5787e352b92a61e0001737d0"}), "d1fca8436e00ae57847182e81fa4b3e0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "437a77a36d58465a8610689515b694b8",
                                                        "5d83b98a5787e352b92a61e0001737d0"}), "1c4bd4ea6a428d5c9c89eeb30809bbd7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a página inicial da área do candidato")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "38c056d38fcc4050970283c59a19ae3d"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Responsividade", "50443eb82577045db52f85c35b0fd63f")}), new System.Collections.Generic.List<string>(new string[] {
                                        "7468bfcc853dea57ac82c50d9228596f",
                                        "5d83b98a5787e352b92a61e0001737d0"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("47cf584e0972965e80b3ae30600f0f93", "Features/Responsiveness.feature", "Fluxo de login completo em 375x812", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5fc6ff7928532d58878bdafe478dc465",
                                                        "b265ce92066aec5db55297bc76abe21c"}), "bcad1c562335855ebe6b39341315a52f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "que acesso a página inicial com cadastro concluído no curso \"Psicologia\" do nível" +
                                                " \"Graduação\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0fd7ca5a3537245b859415fda0162549",
                                                        "b265ce92066aec5db55297bc76abe21c"}), "cad56521c61cc359b4173620b4ed0f6b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "defino a janela para \"375x812\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "47bd32a1ff2f235aabbbd805383afd7d",
                                                        "b265ce92066aec5db55297bc76abe21c"}), "27bccb0bb510de5a8a2764dd16edbc83", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "preencho o usuário e senha válidos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c071d6451c6fb259b2585ba184fb7f24",
                                                        "b265ce92066aec5db55297bc76abe21c"}), "07530b9e737b1c5bba73575270e79c44", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "clico em \"Login\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "437a77a36d58465a8610689515b694b8",
                                                        "b265ce92066aec5db55297bc76abe21c"}), "c7faef7a95557c579e2a8e523d22bab6", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "devo visualizar a página inicial da área do candidato")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Login", "38c056d38fcc4050970283c59a19ae3d"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@Responsividade", "50443eb82577045db52f85c35b0fd63f")}), new System.Collections.Generic.List<string>(new string[] {
                                        "7468bfcc853dea57ac82c50d9228596f",
                                        "b265ce92066aec5db55297bc76abe21c"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(TestesDeResponsividadeFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(TestesDeResponsividadeFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(TestesDeResponsividadeFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Fluxo de login completo em <resolucao>")]
        [global::NUnit.Framework.CategoryAttribute("Login")]
        [global::NUnit.Framework.CategoryAttribute("Responsividade")]
        [global::NUnit.Framework.TestCaseAttribute("Mestrado em Engenharia de Software", "Pós-graduação", "1366x768", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("Direito", "Graduação", "1920x1080", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("Psicologia", "Graduação", "375x812", "2", null)]
        public async global::System.Threading.Tasks.Task FluxoDeLoginCompletoEmResolucao(string curso, string nivel, string resolucao, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Login",
                    "Responsividade"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("curso", curso);
            argumentsOfScenario.Add("nivel", nivel);
            argumentsOfScenario.Add("resolucao", resolucao);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fluxo de login completo em <resolucao>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await testRunner.GivenAsync(string.Format("que acesso a página inicial com cadastro concluído no curso \"{0}\" do nível \"{1}\"", curso, nivel), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
  await testRunner.WhenAsync(string.Format("defino a janela para \"{0}\"", resolucao), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
  await testRunner.AndAsync("preencho o usuário e senha válidos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
  await testRunner.AndAsync("clico em \"Login\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
  await testRunner.ThenAsync("devo visualizar a página inicial da área do candidato", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
